spring.application.name=vetcare360-backend
server.port=${PORT:8080}

# URL del emisor de tokens en Cognito/Azure
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-2.amazonaws.com/us-east-2_ZhTULhf5B

logging.level.org.springframework.security=DEBUG